# Generated by Django 6.1.1 on 2026-10-06 08:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.CharField(help_text='Ex: Septembre 2026', max_length=50, verbose_name='Mois')),
                ('montant_initial', models.DecimalField(decimal_places=2, help_text='Montant total alloué pour le mois', max_digits=12, verbose_name='Montant initial du budget')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('cree_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budgets_crees', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
            ],
            options={
                'verbose_name': 'Budget Mensuel',
                'verbose_name_plural': 'Budgets Mensuels',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Date de la dépense')),
                ('designation', models.CharField(help_text='Description de la dépense', max_length=255, verbose_name='Désignation')),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text="Prix à l'unité", max_digits=10, verbose_name='Prix unitaire')),
                ('quantite', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='budget_app.budgetmensuel', verbose_name='Budget mensuel')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='budgetmensuel',
            constraint=models.UniqueConstraint(fields=('mois',), name='unique_budget_per_month'),
        ),
    ]
