# Generated by Django 6.1.1 on 2026-10-08 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissionUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peut_lire', models.BooleanField(default=True, help_text='Peut consulter le tableau de bord et les dépenses.', verbose_name='Lecture')),
                ('peut_ecrire', models.BooleanField(default=False, help_text='Peut ajouter de nouvelles dépenses (aucune modification possible).', verbose_name='Écriture')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('modifie_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_accordees', to=settings.AUTH_USER_MODEL, verbose_name='Accordée par')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permission_budget', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Autorisation d'accès",
                'verbose_name_plural': "Autorisations d'accès (lecture / écriture)",
                'ordering': ['utilisateur__username'],
            },
        ),
        migrations.CreateModel(
            name='ProfilUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(help_text='Numéro utilisé pour se connecter. Ex : 0384160133', max_length=20, unique=True, verbose_name='Téléphone')),
                ('fonction', models.CharField(blank=True, help_text="Facultatif : rôle dans l'association.", max_length=100, verbose_name='Fonction')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Modifié le')),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Profil utilisateur',
                'verbose_name_plural': 'Profils utilisateurs',
                'ordering': ['utilisateur__username'],
            },
        ),
    ]
