# Generated by Django 6.1.1 on 2026-10-09 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0002_permissionutilisateur'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=80, unique=True, verbose_name='Nom de la catégorie')),
                ('icone', models.CharField(blank=True, default='bi-tag', help_text="Nom d'icône Bootstrap Icons, ex : bi-basket2, bi-box-seam.", max_length=40, verbose_name='Icône')),
                ('couleur', models.CharField(blank=True, default='#2563eb', help_text='Couleur au format hexadécimal, ex : #2563eb.', max_length=7, verbose_name='Couleur')),
                ('ordre', models.PositiveSmallIntegerField(default=0, help_text='Les valeurs les plus basses apparaissent en premier.', verbose_name="Ordre d'affichage")),
                ('active', models.BooleanField(default=True, help_text="Décochez pour masquer la catégorie sans effacer l'historique.", verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catégorie de budget',
                'verbose_name_plural': 'Catégories de budget',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.AddField(
            model_name='depense',
            name='categorie',
            field=models.ForeignKey(blank=True, help_text='Poste de rattachement (courses, provisions...).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depenses', to='budget_app.categoriebudget', verbose_name='Catégorie'),
        ),
        migrations.CreateModel(
            name='RepartitionCategorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Montant alloué (Ar)')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Précision')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartitions', to='budget_app.budgetmensuel', verbose_name='Budget mensuel')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repartitions', to='budget_app.categoriebudget', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Répartition par catégorie',
                'verbose_name_plural': 'Répartition par catégorie',
                'ordering': ['categorie__ordre', 'categorie__nom'],
                'constraints': [models.UniqueConstraint(fields=('budget', 'categorie'), name='unique_repartition_par_categorie')],
            },
        ),
    ]
