# Generated by Django 6.1.1 on 2026-10-09 14:43

from django.db import migrations, models

from budget_app.couleurs import couleur_connue


def hexadecimaux_vers_noms(apps, schema_editor):
    """
    Convertit les anciens codes hexadécimal (#2563eb) en noms de palette
    (bleu, cyan-degrade…).

    Les catégories existantes gardent ainsi leur couleur d'origine : la
    conversion se fait par correspondance exacte, et par teinte la plus proche
    pour un code inconnu.
    """
    CategorieBudget = apps.get_model('budget_app', 'CategorieBudget')
    converties = 0
    for categorie in CategorieBudget.objects.all():
        nom = couleur_connue(categorie.couleur)
        if nom != categorie.couleur:
            categorie.couleur = nom
            categorie.save(update_fields=['couleur'])
            converties += 1
    if converties:
        print(f"  {converties} couleur(s) convertie(s) vers la palette nommée")


def noms_vers_hexadecimaux(apps, schema_editor):
    """Operation inverse, pour pouvoir annuler la migration sans perte."""
    from budget_app.couleurs import teinte_debut

    CategorieBudget = apps.get_model('budget_app', 'CategorieBudget')
    for categorie in CategorieBudget.objects.all():
        categorie.couleur = teinte_debut(categorie.couleur)
        categorie.save(update_fields=['couleur'])


class Migration(migrations.Migration):

    dependencies = [
        ('budget_app', '0003_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriebudget',
            name='couleur',
            field=models.CharField(default='bleu', help_text='Choisir une couleur ou un dégradé dans la liste.', max_length=30, verbose_name='Couleur'),
        ),
        # L alteration du champ n'agit pas sur les valeurs déjà enregistrées :
        # SQLite est laxiste sur la longueur, mais les anciennes valeurs
        # resteraient des codes hexadécimal. D'où la conversion explicite.
        migrations.RunPython(hexadecimaux_vers_noms, noms_vers_hexadecimaux),
    ]
